# Global build settings
[build]
  publish = "build"
  # https://docs.netlify.com/configure-builds/file-based-configuration/#inject-environment-variable-values
  command = "sed -i s/API_URL_PLACEHOLDER/$API_URL/g netlify.toml && yarn build"

# Redirects
[[redirects]]
  from = "/api/v1/*"
  to = "API_URL_PLACEHOLDER/api/v1/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
